# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ubbThqeUdoAzIDDvxinSMu6DJeVOrulN
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q \
    "transformers>=4.50.0,<6" \
    peft \
    accelerate \
    bitsandbytes \
    huggingface_hub

from google.colab import drive

drive.mount("/content/drive")

from huggingface_hub import login

login()

import sys
import torch
import pandas as pd
import PIL
import transformers
import peft
import accelerate
import bitsandbytes as bnb

from PIL import Image

print("=" * 80)
print("COLAB QLoRA ENVIRONMENT")
print("=" * 80)

print("Python       :", sys.version.split()[0])
print("PyTorch      :", torch.__version__)
print("CUDA         :", torch.version.cuda)
print("Pandas       :", pd.__version__)
print("Pillow       :", PIL.__version__)
print("Transformers :", transformers.__version__)
print("PEFT         :", peft.__version__)
print("Accelerate   :", accelerate.__version__)
print("bitsandbytes :", bnb.__version__)

print("\nCUDA available:", torch.cuda.is_available())

if not torch.cuda.is_available():
    raise RuntimeError("CUDA GPU was not detected.")

print("GPU          :", torch.cuda.get_device_name(0))

gpu_memory = (
    torch.cuda.get_device_properties(0).total_memory
    / 1024**3
)

print(f"GPU memory   : {gpu_memory:.2f} GB")
print("BF16 support :", torch.cuda.is_bf16_supported())

assert "A100" in torch.cuda.get_device_name(0), (
    "Expected an A100 runtime."
)

print("\nEnvironment check passed.")

# Commented out IPython magic to ensure Python compatibility.
# ==================================================================================================
# PATIENT 24 RAW EEG TOPOMAP CLASSIFICATION
# MEDGEMMA-4B-IT + QLoRA
# GOOGLE COLAB / A100 VERSION
# ==================================================================================================

import os
import re
import gc
import sys
import json
import math
import time
import random
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

from PIL import Image

import torch

from torch.utils.data import Dataset, DataLoader

from tqdm import tqdm

from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    f1_score,
    balanced_accuracy_score,
)

from huggingface_hub import whoami

from transformers import (
    AutoProcessor,
    AutoModelForMultimodalLM,
    BitsAndBytesConfig,
    get_linear_schedule_with_warmup,
)

from peft import (
    LoraConfig,
    get_peft_model,
    prepare_model_for_kbit_training,
    PeftModel,
)

import transformers
import peft
import bitsandbytes as bnb


# ==================================================================================================
# 1. CLEAN GPU
# ==================================================================================================

gc.collect()

if torch.cuda.is_available():
    torch.cuda.empty_cache()


# ==================================================================================================
# 2. GPU
# ==================================================================================================

if not torch.cuda.is_available():
    raise RuntimeError("CUDA GPU was not detected.")

DEVICE = torch.device("cuda:0")

GPU_NAME = torch.cuda.get_device_name(0)

GPU_MEMORY_GB = (
    torch.cuda.get_device_properties(0).total_memory
    /
    1024**3
)

print("=" * 100)
print("GPU")
print("=" * 100)

print("GPU:", GPU_NAME)
print(f"GPU memory: {GPU_MEMORY_GB:.2f} GB")

if torch.cuda.is_bf16_supported():
    MODEL_DTYPE = torch.bfloat16
    PRECISION_NAME = "bfloat16"
else:
    MODEL_DTYPE = torch.float16
    PRECISION_NAME = "float16"

print("Compute dtype:", PRECISION_NAME)

torch.backends.cuda.matmul.allow_tf32 = True


# ==================================================================================================
# 3. PACKAGE VERSIONS
# ==================================================================================================

print("\n" + "=" * 100)
print("PACKAGE VERSIONS")
print("=" * 100)

print("Python       :", sys.version.split()[0])
print("PyTorch      :", torch.__version__)
print("Transformers :", transformers.__version__)
print("PEFT         :", peft.__version__)
print("bitsandbytes :", bnb.__version__)


# ==================================================================================================
# 4. HUGGING FACE LOGIN CHECK
# ==================================================================================================

print("\n" + "=" * 100)
print("HUGGING FACE LOGIN")
print("=" * 100)

try:
    hf_info = whoami()
    print("Logged in as:", hf_info["name"])

except Exception as error:
    raise RuntimeError(
        "Hugging Face authentication is not available. "
        "Run login() in the previous Colab cell."
    ) from error


# ==================================================================================================
# 5. DRIVE ROOT
# ==================================================================================================

DRIVE_ROOT = "/content/drive/MyDrive"

if not os.path.isdir(DRIVE_ROOT):
    raise FileNotFoundError(
        "Google Drive is not mounted at /content/drive/MyDrive"
    )


# ==================================================================================================
# 6. AUTO-FIND CSV FILE
# ==================================================================================================

def find_exact_file(filename):

    matches = []

    print(f"\nSearching Drive for: {filename}")

    for root, dirs, files in os.walk(DRIVE_ROOT):

        if filename in files:

            full_path = os.path.join(
                root,
                filename,
            )

            matches.append(full_path)

    if not matches:
        return None

    matches = sorted(
        matches,
        key=lambda x: os.path.getmtime(x),
        reverse=True,
    )

    print(f"Found {len(matches)} match(es):")

    for match in matches:
        print(" ", match)

    print("\nUsing:")
    print(matches[0])

    return matches[0]


# ==================================================================================================
# 7. FIND RAW TRAIN / TEST CSVs
# ==================================================================================================

TRAINING_METADATA_CSV = find_exact_file(
    "Patient_24_RAW_training_metadata.csv"
)

TESTING_METADATA_CSV = find_exact_file(
    "Patient_24_RAW_blinded_test_labels.csv"
)

if TRAINING_METADATA_CSV is None:
    raise FileNotFoundError(
        "Could not find Patient_24_RAW_training_metadata.csv in Google Drive."
    )

if TESTING_METADATA_CSV is None:
    raise FileNotFoundError(
        "Could not find Patient_24_RAW_blinded_test_labels.csv in Google Drive."
    )


# ==================================================================================================
# 8. TRY TO FIND THE EXACT LoRA TRAIN / VALIDATION SPLITS
#
# If these were uploaded to Drive, QLoRA will use them directly.
# Otherwise the exact same seed-42 class-stratified split is recreated.
# ==================================================================================================

EXISTING_LORA_TRAIN_SPLIT = find_exact_file(
    "Patient_24_RAW_LoRA_actual_train.csv"
)

EXISTING_LORA_VALIDATION_SPLIT = find_exact_file(
    "Patient_24_RAW_LoRA_validation.csv"
)


# ==================================================================================================
# 9. OUTPUT DIRECTORY
# ==================================================================================================

OUTPUT_ROOT = os.path.join(
    DRIVE_ROOT,
    "Patient_24_RAW_MedGemma4B_QLoRA_r8_a16_50epochs_patience7",
)

BEST_ADAPTER_ROOT = os.path.join(
    OUTPUT_ROOT,
    "best_qlora_checkpoints",
)

os.makedirs(
    BEST_ADAPTER_ROOT,
    exist_ok=True,
)

TRAIN_SPLIT_CSV = os.path.join(
    OUTPUT_ROOT,
    "Patient_24_RAW_QLoRA_actual_train.csv",
)

VALIDATION_SPLIT_CSV = os.path.join(
    OUTPUT_ROOT,
    "Patient_24_RAW_QLoRA_validation.csv",
)

TRAINING_HISTORY_CSV = os.path.join(
    OUTPUT_ROOT,
    "Patient_24_RAW_QLoRA_training_history.csv",
)

FINAL_PREDICTIONS_CSV = os.path.join(
    OUTPUT_ROOT,
    "Patient_24_RAW_QLoRA_final_test_predictions.csv",
)

FINAL_METRICS_JSON = os.path.join(
    OUTPUT_ROOT,
    "Patient_24_RAW_QLoRA_final_metrics.json",
)

EXPERIMENT_CONFIG_JSON = os.path.join(
    OUTPUT_ROOT,
    "Patient_24_RAW_QLoRA_experiment_config.json",
)

TARGET_MODULES_TXT = os.path.join(
    OUTPUT_ROOT,
    "Patient_24_RAW_QLoRA_target_modules.txt",
)

CONFUSION_MATRIX_CSV = os.path.join(
    OUTPUT_ROOT,
    "Patient_24_RAW_QLoRA_confusion_matrix.csv",
)


# ==================================================================================================
# 10. MODEL
# ==================================================================================================

MODEL_ID = "google/medgemma-4b-it"


# ==================================================================================================
# 11. EXACT SYSTEM PROMPT FROM PATIENT 24 RAW LoRA
# DO NOT CHANGE
# ==================================================================================================

SYSTEM_PROMPT = """
You are a strict vision-language classifier for EEG seizure detection.
Classify each EEG topomap image into exactly one of two labels:
Seizure
Non-seizure
Return only the final label. Do not provide explanation, puntuation, confidence score or extra text.
""".strip()


# ==================================================================================================
# 12. EXACT USER PROMPT FROM PATIENT 24 RAW LoRA
# DO NOT CHANGE
# ==================================================================================================

USER_PROMPT = """
You are an expert in identifying seizure patterns from EEG variance topomaps.The attached image represents a 2 second EEG segment
Classify the provided fixed-scale EEG variance topomap as one of the following:

seizure
non-seizure

The raw EEG signal was divided into fixed time windows. For each window, the variance of every bipolar EEG channel was calculated directly from the raw EEG values.
Each channel variance value was positioned at the midpoint between the two electrodes forming that bipolar channel. These values were spatially interpolated to create the EEG topomap.
All topomaps use the same fixed color scale, allowing direct comparison across images. Yellow regions indicate higher EEG variance, while dark purple regions indicate lower EEG variance.
Classify the image based on the visible variance intensity and spatial distribution. Consider whether high-variance activity is focal or widespread and symmetric or asymmetric.
Evaluate these characteristics together rather than using any single feature as a definitive rule.
""".strip()


# ==================================================================================================
# 13. RANDOM SEED
# ==================================================================================================

RANDOM_SEED = 42


def set_all_seeds(seed):

    random.seed(seed)

    np.random.seed(seed)

    torch.manual_seed(seed)

    if torch.cuda.is_available():

        torch.cuda.manual_seed(seed)

        torch.cuda.manual_seed_all(seed)


set_all_seeds(
    RANDOM_SEED
)


# ==================================================================================================
# 14. LoRA HYPERPARAMETERS
#
# SAME AS THE LoRA COMPARISON
# ==================================================================================================

LORA_R = 8

LORA_ALPHA = 16

LORA_DROPOUT = 0.05

LORA_TARGET_LEAF_NAMES = [
    "q_proj",
    "k_proj",
    "v_proj",
    "o_proj",
]


# ==================================================================================================
# 15. TRAINING HYPERPARAMETERS
#
# SAME AS LoRA
# ==================================================================================================

NUM_EPOCHS = 50

EARLY_STOPPING_PATIENCE = 7

LEARNING_RATE = 1e-4

WEIGHT_DECAY = 0.01

TRAIN_BATCH_SIZE = 1

VALIDATION_BATCH_SIZE = 1

GRADIENT_ACCUMULATION_STEPS = 8

MAX_GRAD_NORM = 1.0

WARMUP_RATIO = 0.05

MAX_NEW_TOKENS = 8

NUM_WORKERS = 0


# ==================================================================================================
# 16. EXPECTED COUNTS
# ==================================================================================================

EXPECTED_FULL_TRAIN_SEIZURE = 100
EXPECTED_FULL_TRAIN_NON_SEIZURE = 400

EXPECTED_ACTUAL_TRAIN_SEIZURE = 80
EXPECTED_ACTUAL_TRAIN_NON_SEIZURE = 320

EXPECTED_VALIDATION_SEIZURE = 20
EXPECTED_VALIDATION_NON_SEIZURE = 80

EXPECTED_TEST_SEIZURE = 100
EXPECTED_TEST_NON_SEIZURE = 400


# ==================================================================================================
# 17. LABEL NORMALIZATION
# ==================================================================================================

def normalize_ground_truth_label(value):

    if pd.isna(value):
        return None

    if isinstance(
        value,
        (
            int,
            np.integer,
        ),
    ):

        if int(value) == 1:
            return 1

        if int(value) == 0:
            return 0

    if isinstance(
        value,
        (
            float,
            np.floating,
        ),
    ):

        if float(value) == 1.0:
            return 1

        if float(value) == 0.0:
            return 0

    text = str(value).strip().lower()

    text = text.replace("_", " ")

    text = text.replace("–", "-")

    text = re.sub(
        r"\s+",
        " ",
        text,
    )

    # Non-seizure MUST be checked first.
    if text in {
        "0",
        "0.0",
        "non seizure",
        "non-seizure",
        "nonseizure",
        "normal",
        "interictal",
        "ns",
    }:
        return 0

    if (
        "non" in text
        and
        "seizure" in text
    ):
        return 0

    if text in {
        "1",
        "1.0",
        "seizure",
        "ictal",
        "sz",
    }:
        return 1

    if "seizure" in text:
        return 1

    return None


# ==================================================================================================
# 18. DETECT IMAGE COLUMN
# ==================================================================================================

def detect_image_path_column(df, dataset_type):

    if dataset_type == "test":

        candidates = [
            "blinded_image_path",
            "blinded_topomap_path",
            "blinded_path",
            "fine_tuning_image_path",
            "image_path",
            "selected_image_path",
            "original_image_path",
            "file_path",
            "filepath",
            "path",
        ]

    else:

        candidates = [
            "fine_tuning_image_path",
            "image_path",
            "selected_image_path",
            "blinded_image_path",
            "blinded_topomap_path",
            "blinded_path",
            "original_image_path",
            "file_path",
            "filepath",
            "path",
        ]

    for candidate in candidates:

        if candidate in df.columns:
            return candidate

    for column in df.columns:

        lower = str(column).lower()

        if (
            "path" in lower
            and
            (
                "image" in lower
                or
                "topomap" in lower
                or
                "blinded" in lower
            )
        ):
            return column

    raise ValueError(
        f"Could not detect an image path column.\nColumns:\n{list(df.columns)}"
    )


# ==================================================================================================
# 19. DETECT LABEL COLUMN
# ==================================================================================================

def detect_label_column(df):

    candidates = [
        "standard_label",
        "label",
        "Label",
        "target",
        "class_label",
        "fine_tuning_class",
        "class_name",
        "class",
        "category",
        "true_label",
        "ground_truth",
    ]

    for candidate in candidates:

        if candidate in df.columns:
            return candidate

    for column in df.columns:

        lower = str(column).lower()

        if (
            "label" in lower
            or
            lower == "class"
        ):
            return column

    raise ValueError(
        f"Could not detect label column.\nColumns:\n{list(df.columns)}"
    )


# ==================================================================================================
# 20. GOOGLE DRIVE IMAGE PATH RESOLUTION
#
# Handles CSVs whose image paths still contain Windows C:\\... paths.
# ==================================================================================================

IMAGE_EXTENSIONS = {
    ".png",
    ".jpg",
    ".jpeg",
    ".bmp",
    ".webp",
}


def windows_safe_basename(value):

    text = str(value).strip()

    text = text.strip('"').strip("'")

    text = text.replace("\\", "/")

    return text.split("/")[-1]


def build_image_index(search_root):

    print("\nBuilding image index from:")
    print(search_root)

    index = {}

    total = 0

    for root, dirs, files in os.walk(search_root):

        for filename in files:

            extension = os.path.splitext(
                filename
            )[1].lower()

            if extension not in IMAGE_EXTENSIONS:
                continue

            full_path = os.path.join(
                root,
                filename,
            )

            index.setdefault(
                filename.lower(),
                [],
            ).append(
                full_path
            )

            total += 1

    print("Images indexed:", total)

    return index


def resolve_paths_for_dataframe(
    df,
    image_column,
    csv_path,
):

    original_values = df[
        image_column
    ].astype(str).tolist()

    # First determine whether all paths already work.
    direct_paths = []

    all_direct = True

    for value in original_values:

        cleaned = str(value).strip().strip('"').strip("'")

        if os.path.isfile(cleaned):

            direct_paths.append(cleaned)

        else:

            all_direct = False
            break

    if all_direct:

        df["_image_path"] = direct_paths

        print("\nAll CSV image paths already exist.")

        return df

    # Search near the CSV first.
    csv_folder = os.path.dirname(
        csv_path
    )

    candidate_roots = [
        csv_folder,
        os.path.dirname(csv_folder),
        os.path.dirname(
            os.path.dirname(csv_folder)
        ),
        DRIVE_ROOT,
    ]

    # Remove duplicates while preserving order.
    candidate_roots = list(
        dict.fromkeys(
            candidate_roots
        )
    )

    unresolved = list(
        range(
            len(original_values)
        )
    )

    resolved = {
    }

    for search_root in candidate_roots:

        if not unresolved:
            break

        if not os.path.isdir(search_root):
            continue

        image_index = build_image_index(
            search_root
        )

        still_unresolved = []

        for row_index in unresolved:

            original = original_values[
                row_index
            ]

            filename = windows_safe_basename(
                original
            )

            matches = image_index.get(
                filename.lower(),
                [],
            )

            if len(matches) == 1:

                resolved[
                    row_index
                ] = matches[0]

                continue

            if len(matches) > 1:

                original_normalized = (
                    original
                    .replace("\\", "/")
                    .lower()
                )

                original_parts = [
                    part
                    for part
                    in original_normalized.split("/")
                    if part
                ]

                chosen = None

                # Try progressively longer suffixes.
                for suffix_length in [
                    4,
                    3,
                    2,
                ]:

                    if len(original_parts) < suffix_length:
                        continue

                    suffix = "/".join(
                        original_parts[
                            -suffix_length:
                        ]
                    )

                    suffix_matches = [
                        match
                        for match
                        in matches
                        if match.replace(
                            "\\",
                            "/",
                        ).lower().endswith(
                            suffix
                        )
                    ]

                    if len(suffix_matches) == 1:

                        chosen = suffix_matches[0]

                        break

                if chosen is not None:

                    resolved[
                        row_index
                    ] = chosen

                    continue

            still_unresolved.append(
                row_index
            )

        unresolved = still_unresolved

    if unresolved:

        print("\nUNRESOLVED IMAGES:")

        for row_index in unresolved[:30]:

            print(
                row_index,
                original_values[
                    row_index
                ],
            )

        raise FileNotFoundError(
            f"{len(unresolved)} image paths could not be resolved in Google Drive."
        )

    resolved_paths = [
        resolved[index]
        for index
        in range(
            len(original_values)
        )
    ]

    df["_image_path"] = resolved_paths

    return df


# ==================================================================================================
# 21. LOAD + STANDARDIZE CSV
# ==================================================================================================

def load_and_standardize_metadata(
    csv_path,
    dataset_name,
    dataset_type,
):

    print("\n" + "=" * 100)
    print("LOADING:", dataset_name)
    print("=" * 100)

    if not os.path.isfile(csv_path):

        raise FileNotFoundError(
            csv_path
        )

    df = pd.read_csv(
        csv_path
    )

    print("CSV:", csv_path)
    print("Rows:", len(df))
    print("Columns:", list(df.columns))

    image_column = detect_image_path_column(
        df,
        dataset_type,
    )

    label_column = detect_label_column(
        df
    )

    print("Image column:", image_column)
    print("Label column:", label_column)

    df["_label"] = df[
        label_column
    ].apply(
        normalize_ground_truth_label
    )

    if df["_label"].isna().any():

        bad = df[
            df["_label"].isna()
        ]

        print(
            bad[
                [label_column]
            ].drop_duplicates()
        )

        raise ValueError(
            "Some labels could not be interpreted."
        )

    df["_label"] = df[
        "_label"
    ].astype(int)

    df = resolve_paths_for_dataframe(
        df,
        image_column,
        csv_path,
    )

    missing = [
        path
        for path
        in df["_image_path"]
        if not os.path.isfile(path)
    ]

    if missing:

        raise FileNotFoundError(
            f"{len(missing)} images are missing."
        )

    duplicate_count = int(
        df[
            "_image_path"
        ].duplicated().sum()
    )

    if duplicate_count > 0:

        raise ValueError(
            f"{duplicate_count} duplicate image paths were detected."
        )

    seizure_count = int(
        (
            df["_label"] == 1
        ).sum()
    )

    non_seizure_count = int(
        (
            df["_label"] == 0
        ).sum()
    )

    print("\nSeizure     :", seizure_count)
    print("Non-seizure :", non_seizure_count)
    print("Total        :", len(df))

    return (
        df,
        image_column,
        label_column,
    )


# ==================================================================================================
# 22. LOAD ORIGINAL TRAINING POOL
# ==================================================================================================

(
    full_training_df,
    training_image_column,
    training_label_column,
) = load_and_standardize_metadata(
    TRAINING_METADATA_CSV,
    "Patient 24 RAW training pool",
    "train",
)


# ==================================================================================================
# 23. VERIFY TRAINING COUNTS
# ==================================================================================================

full_train_s = int(
    (
        full_training_df["_label"] == 1
    ).sum()
)

full_train_ns = int(
    (
        full_training_df["_label"] == 0
    ).sum()
)

assert full_train_s == EXPECTED_FULL_TRAIN_SEIZURE, (
    f"Expected {EXPECTED_FULL_TRAIN_SEIZURE} seizures, got {full_train_s}"
)

assert full_train_ns == EXPECTED_FULL_TRAIN_NON_SEIZURE, (
    f"Expected {EXPECTED_FULL_TRAIN_NON_SEIZURE} non-seizures, got {full_train_ns}"
)


# ==================================================================================================
# 24. TRAIN / VALIDATION SPLIT
#
# Exact previous LoRA split is preferred when available.
# ==================================================================================================

if (
    EXISTING_LORA_TRAIN_SPLIT is not None
    and
    EXISTING_LORA_VALIDATION_SPLIT is not None
):

    print("\n" + "=" * 100)
    print("USING EXACT SAVED LoRA TRAIN / VALIDATION SPLITS")
    print("=" * 100)

    (
        actual_train_df,
        _,
        _,
    ) = load_and_standardize_metadata(
        EXISTING_LORA_TRAIN_SPLIT,
        "Existing Patient 24 RAW LoRA actual training split",
        "train",
    )

    (
        validation_df,
        _,
        _,
    ) = load_and_standardize_metadata(
        EXISTING_LORA_VALIDATION_SPLIT,
        "Existing Patient 24 RAW LoRA validation split",
        "train",
    )

else:

    print("\n" + "=" * 100)
    print("RECREATING SAME SEED-42 TRAIN / VALIDATION SPLIT")
    print("=" * 100)

    seizure_pool = full_training_df[
        full_training_df["_label"] == 1
    ].copy()

    non_seizure_pool = full_training_df[
        full_training_df["_label"] == 0
    ].copy()

    seizure_pool = seizure_pool.sample(
        frac=1,
        random_state=RANDOM_SEED,
    ).reset_index(
        drop=True
    )

    non_seizure_pool = non_seizure_pool.sample(
        frac=1,
        random_state=RANDOM_SEED,
    ).reset_index(
        drop=True
    )

    actual_train_seizure = seizure_pool.iloc[
        :EXPECTED_ACTUAL_TRAIN_SEIZURE
    ].copy()

    actual_train_non_seizure = non_seizure_pool.iloc[
        :EXPECTED_ACTUAL_TRAIN_NON_SEIZURE
    ].copy()

    validation_seizure = seizure_pool.iloc[
        EXPECTED_ACTUAL_TRAIN_SEIZURE:
        EXPECTED_ACTUAL_TRAIN_SEIZURE
        +
        EXPECTED_VALIDATION_SEIZURE
    ].copy()

    validation_non_seizure = non_seizure_pool.iloc[
        EXPECTED_ACTUAL_TRAIN_NON_SEIZURE:
        EXPECTED_ACTUAL_TRAIN_NON_SEIZURE
        +
        EXPECTED_VALIDATION_NON_SEIZURE
    ].copy()

    actual_train_df = pd.concat(
        [
            actual_train_seizure,
            actual_train_non_seizure,
        ],
        ignore_index=True,
    )

    validation_df = pd.concat(
        [
            validation_seizure,
            validation_non_seizure,
        ],
        ignore_index=True,
    )

    actual_train_df = actual_train_df.sample(
        frac=1,
        random_state=RANDOM_SEED,
    ).reset_index(
        drop=True
    )

    validation_df = validation_df.sample(
        frac=1,
        random_state=RANDOM_SEED,
    ).reset_index(
        drop=True
    )


# ==================================================================================================
# 25. VERIFY SPLIT COUNTS
# ==================================================================================================

train_s = int(
    (
        actual_train_df["_label"] == 1
    ).sum()
)

train_ns = int(
    (
        actual_train_df["_label"] == 0
    ).sum()
)

val_s = int(
    (
        validation_df["_label"] == 1
    ).sum()
)

val_ns = int(
    (
        validation_df["_label"] == 0
    ).sum()
)

assert train_s == 80
assert train_ns == 320
assert val_s == 20
assert val_ns == 80

train_val_overlap = set(
    actual_train_df["_image_path"]
).intersection(
    set(
        validation_df["_image_path"]
    )
)

assert len(
    train_val_overlap
) == 0

print("\nACTUAL TRAINING")
print("Seizure     :", train_s)
print("Non-seizure :", train_ns)
print("Total        :", len(actual_train_df))

print("\nVALIDATION")
print("Seizure     :", val_s)
print("Non-seizure :", val_ns)
print("Total        :", len(validation_df))

print("\nTrain/validation overlap:", len(train_val_overlap))


# ==================================================================================================
# 26. SAVE QLoRA SPLITS
# ==================================================================================================

actual_train_df.to_csv(
    TRAIN_SPLIT_CSV,
    index=False,
)

validation_df.to_csv(
    VALIDATION_SPLIT_CSV,
    index=False,
)


# ==================================================================================================
# 27. LOAD BLINDED TEST
# ==================================================================================================

(
    testing_df,
    testing_image_column,
    testing_label_column,
) = load_and_standardize_metadata(
    TESTING_METADATA_CSV,
    "Patient 24 RAW blinded testing",
    "test",
)


test_s = int(
    (
        testing_df["_label"] == 1
    ).sum()
)

test_ns = int(
    (
        testing_df["_label"] == 0
    ).sum()
)

assert test_s == EXPECTED_TEST_SEIZURE
assert test_ns == EXPECTED_TEST_NON_SEIZURE


# ==================================================================================================
# 28. TRAIN / TEST LEAKAGE CHECK
# ==================================================================================================

def normalize_identity_value(value):

    if pd.isna(value):
        return None

    text = str(value).strip()

    try:

        number = float(text)

        if number.is_integer():
            return str(
                int(number)
            )

    except Exception:
        pass

    return text.lower()


def check_train_test_identity_leakage(
    train_df,
    test_df,
):

    preferred_columns = [
        "global_serial_id",
        "global_serial",
        "Global_Serial_ID",
        "Global_Serial",
        "Serial",
        "serial",
        "original_image_path",
        "original_image_name",
    ]

    for column in preferred_columns:

        if (
            column in train_df.columns
            and
            column in test_df.columns
        ):

            train_ids = {
                normalize_identity_value(value)
                for value
                in train_df[column]
                if normalize_identity_value(value) is not None
            }

            test_ids = {
                normalize_identity_value(value)
                for value
                in test_df[column]
                if normalize_identity_value(value) is not None
            }

            overlap = train_ids.intersection(
                test_ids
            )

            print(
                "\nLeakage column:",
                column,
            )

            print(
                "Train/test identity overlap:",
                len(overlap),
            )

            if overlap:

                raise RuntimeError(
                    f"DATA LEAKAGE: {len(overlap)} shared samples."
                )

            return column

    warnings.warn(
        "No common global serial/original identity column was available."
    )

    return None


LEAKAGE_ID_COLUMN = check_train_test_identity_leakage(
    full_training_df,
    testing_df,
)

path_overlap = set(
    full_training_df["_image_path"]
).intersection(
    set(
        testing_df["_image_path"]
    )
)

if path_overlap:

    raise RuntimeError(
        "Training and testing contain identical current image paths."
    )

print("Current train/test image-path overlap: 0")


# ==================================================================================================
# 29. DATASET
# ==================================================================================================

class EEGTopomapDataset(Dataset):

    def __init__(
        self,
        dataframe,
    ):

        self.df = dataframe.reset_index(
            drop=True
        )

    def __len__(
        self,
    ):

        return len(
            self.df
        )

    def __getitem__(
        self,
        index,
    ):

        row = self.df.iloc[
            index
        ]

        return {
            "index": int(index),
            "image_path": str(
                row["_image_path"]
            ),
            "label": int(
                row["_label"]
            ),
        }


# ==================================================================================================
# 30. PROCESSOR
# ==================================================================================================

print("\n" + "=" * 100)
print("LOADING MEDGEMMA PROCESSOR")
print("=" * 100)

processor = AutoProcessor.from_pretrained(
    MODEL_ID,
    token=True,
)

if hasattr(
    processor,
    "tokenizer",
):

    processor.tokenizer.padding_side = "right"

print("Processor loaded.")


# ==================================================================================================
# 31. QLoRA 4-BIT CONFIGURATION
#
# THIS IS THE MAIN DIFFERENCE FROM STANDARD LoRA.
# ==================================================================================================

print("\n" + "=" * 100)
print("QLoRA QUANTIZATION CONFIG")
print("=" * 100)

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=MODEL_DTYPE,
)

print("load_in_4bit             : True")
print("bnb_4bit_quant_type      : nf4")
print("bnb_4bit_use_double_quant: True")
print("bnb_4bit_compute_dtype   :", MODEL_DTYPE)


# ==================================================================================================
# 32. LOAD 4-BIT MEDGEMMA
# ==================================================================================================

def load_quantized_medgemma():

    print(
        f"\nLoading {MODEL_ID} in 4-bit NF4..."
    )

    try:

        loaded_model = AutoModelForMultimodalLM.from_pretrained(
            MODEL_ID,
            token=True,
            quantization_config=bnb_config,
            device_map={
                "": 0
            },
            dtype=MODEL_DTYPE,
            low_cpu_mem_usage=True,
            attn_implementation="sdpa",
        )

    except TypeError:

        loaded_model = AutoModelForMultimodalLM.from_pretrained(
            MODEL_ID,
            token=True,
            quantization_config=bnb_config,
            device_map={
                "": 0
            },
            torch_dtype=MODEL_DTYPE,
            low_cpu_mem_usage=True,
            attn_implementation="sdpa",
        )

    return loaded_model


gc.collect()

torch.cuda.empty_cache()

base_model = load_quantized_medgemma()

print("\nSUCCESS: 4-bit MedGemma loaded.")

print(
    "GPU allocated:",
    f"{torch.cuda.memory_allocated() / 1024**3:.2f} GB",
)

print(
    "GPU reserved :",
    f"{torch.cuda.memory_reserved() / 1024**3:.2f} GB",
)


# ==================================================================================================
# 33. PREPARE MODEL FOR K-BIT TRAINING
# ==================================================================================================

print("\n" + "=" * 100)
print("PREPARING MODEL FOR K-BIT TRAINING")
print("=" * 100)

if hasattr(
    base_model.config,
    "use_cache",
):

    base_model.config.use_cache = False


base_model = prepare_model_for_kbit_training(
    base_model,
    use_gradient_checkpointing=True,
)

print("prepare_model_for_kbit_training(): complete")


# ==================================================================================================
# 34. FIND LANGUAGE ATTENTION TARGET MODULES
#
# IMPORTANT:
# Do NOT require torch.nn.Linear here.
# The 4-bit modules are bitsandbytes Linear4bit modules.
# ==================================================================================================

print("\n" + "=" * 100)
print("SEARCHING QLoRA TARGET MODULES")
print("=" * 100)

possible_attention_modules = []

for module_name, module in base_model.named_modules():

    leaf_name = module_name.split(
        "."
    )[-1]

    if leaf_name in LORA_TARGET_LEAF_NAMES:

        possible_attention_modules.append(
            module_name
        )


language_attention_modules = [
    name
    for name
    in possible_attention_modules
    if "language_model" in name.lower()
]


if language_attention_modules:

    LORA_TARGET_MODULES = language_attention_modules

    print(
        "Using language-model q/k/v/o projections."
    )

else:

    LORA_TARGET_MODULES = [
        name
        for name
        in possible_attention_modules
        if (
            "vision" not in name.lower()
            and
            "image_encoder" not in name.lower()
        )
    ]

    warnings.warn(
        "No target names contained 'language_model'; "
        "using q/k/v/o after excluding vision modules."
    )


if not LORA_TARGET_MODULES:

    raise RuntimeError(
        "No language attention modules were found for QLoRA."
    )


print(
    "Target module count:",
    len(
        LORA_TARGET_MODULES
    ),
)

print("\nFirst 20 targets:")

for name in LORA_TARGET_MODULES[:20]:

    print(
        " ",
        name,
    )


with open(
    TARGET_MODULES_TXT,
    "w",
    encoding="utf-8",
) as file:

    for name in LORA_TARGET_MODULES:

        file.write(
            name
            +
            "\n"
        )


# ==================================================================================================
# 35. QLoRA ADAPTER CONFIG
# ==================================================================================================

lora_config = LoraConfig(
    r=LORA_R,
    lora_alpha=LORA_ALPHA,
    lora_dropout=LORA_DROPOUT,
    target_modules=LORA_TARGET_MODULES,
    bias="none",
    inference_mode=False,
)


# ==================================================================================================
# 36. INJECT LoRA ADAPTERS INTO QUANTIZED MODEL
# ==================================================================================================

print("\n" + "=" * 100)
print("INJECTING LoRA INTO 4-BIT MEDGEMMA")
print("=" * 100)

model = get_peft_model(
    base_model,
    lora_config,
)

if hasattr(
    model,
    "enable_input_require_grads",
):

    try:
        model.enable_input_require_grads()

    except Exception:
        pass


# ==================================================================================================
# 37. TRAINABLE PARAMETER REPORT
# ==================================================================================================

model.print_trainable_parameters()

trainable_parameter_count = sum(
    parameter.numel()
    for parameter
    in model.parameters()
    if parameter.requires_grad
)

total_parameter_count = sum(
    parameter.numel()
    for parameter
    in model.parameters()
)

trainable_percentage = (
    100.0
    *
    trainable_parameter_count
    /
    total_parameter_count
)

print(
    f"\nTrainable parameters : {trainable_parameter_count:,}"
)

print(
    f"Total parameters     : {total_parameter_count:,}"
)

print(
    f"Trainable percentage : {trainable_percentage:.6f}%"
)


vision_trainable = [
    name
    for name, parameter
    in model.named_parameters()
    if (
        parameter.requires_grad
        and
        "vision" in name.lower()
    )
]

print(
    "Trainable parameters containing 'vision':",
    len(
        vision_trainable
    ),
)


# ==================================================================================================
# 38. TARGET TEXT
# ==================================================================================================

def label_to_target_text(label):

    if int(label) == 1:
        return "Seizure"

    return "Non-seizure"


# ==================================================================================================
# 39. BUILD PROMPTS
# ==================================================================================================

def build_prompt_messages(
    image,
):

    return [
        {
            "role": "system",
            "content": [
                {
                    "type": "text",
                    "text": SYSTEM_PROMPT,
                }
            ],
        },
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": USER_PROMPT,
                },
                {
                    "type": "image",
                    "image": image,
                },
            ],
        },
    ]


def build_training_messages(
    image,
    target_text,
):

    messages = build_prompt_messages(
        image
    )

    messages.append(
        {
            "role": "assistant",
            "content": [
                {
                    "type": "text",
                    "text": target_text,
                }
            ],
        }
    )

    return messages


# ==================================================================================================
# 40. TRAINING COLLATOR
#
# Only assistant target tokens contribute to loss.
# ==================================================================================================

class MedGemmaTrainingCollator:

    def __init__(
        self,
        processor,
    ):

        self.processor = processor

    def __call__(
        self,
        examples,
    ):

        if len(examples) != 1:

            raise ValueError(
                "This pipeline expects physical batch size = 1."
            )

        example = examples[0]

        image_path = example[
            "image_path"
        ]

        label = int(
            example[
                "label"
            ]
        )

        target_text = label_to_target_text(
            label
        )

        with Image.open(
            image_path
        ) as opened_image:

            image = opened_image.convert(
                "RGB"
            )

            prompt_messages = build_prompt_messages(
                image
            )

            prompt_inputs = self.processor.apply_chat_template(
                prompt_messages,
                add_generation_prompt=True,
                tokenize=True,
                return_dict=True,
                return_tensors="pt",
            )

            prompt_length = int(
                prompt_inputs[
                    "input_ids"
                ].shape[
                    1
                ]
            )

            full_messages = build_training_messages(
                image,
                target_text,
            )

            full_inputs = self.processor.apply_chat_template(
                full_messages,
                add_generation_prompt=False,
                tokenize=True,
                return_dict=True,
                return_tensors="pt",
            )

        full_ids = full_inputs[
            "input_ids"
        ]

        prompt_ids = prompt_inputs[
            "input_ids"
        ]

        if full_ids.shape[1] <= prompt_length:

            raise RuntimeError(
                "Full sequence contains no assistant target tokens."
            )

        if not torch.equal(
            full_ids[
                :,
                :prompt_length
            ],
            prompt_ids,
        ):

            raise RuntimeError(
                "MedGemma chat-template prefix mismatch. "
                "Stopping to avoid incorrect loss masking."
            )

        labels = full_ids.clone()

        labels[
            :,
            :prompt_length
        ] = -100

        if int(
            (
                labels != -100
            ).sum()
        ) <= 0:

            raise RuntimeError(
                "No target tokens remain after loss masking."
            )

        full_inputs[
            "labels"
        ] = labels

        return full_inputs


# ==================================================================================================
# 41. DATASETS + DATALOADERS
# ==================================================================================================

train_dataset = EEGTopomapDataset(
    actual_train_df
)

validation_dataset = EEGTopomapDataset(
    validation_df
)

training_collator = MedGemmaTrainingCollator(
    processor
)


train_generator = torch.Generator()

train_generator.manual_seed(
    RANDOM_SEED
)


train_loader = DataLoader(
    train_dataset,
    batch_size=TRAIN_BATCH_SIZE,
    shuffle=True,
    generator=train_generator,
    num_workers=NUM_WORKERS,
    collate_fn=training_collator,
    pin_memory=False,
)


validation_loss_loader = DataLoader(
    validation_dataset,
    batch_size=VALIDATION_BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    collate_fn=training_collator,
    pin_memory=False,
)


# ==================================================================================================
# 42. MOVE INPUTS TO A100
# ==================================================================================================

def move_batch_to_device(
    batch,
):

    moved = {}

    for key, value in batch.items():

        if not torch.is_tensor(
            value
        ):

            moved[key] = value

            continue

        if value.dtype.is_floating_point:

            moved[key] = value.to(
                device=DEVICE,
                dtype=MODEL_DTYPE,
            )

        else:

            moved[key] = value.to(
                DEVICE
            )

    return moved


# ==================================================================================================
# 43. AUTOCAST
# ==================================================================================================

def autocast_context():

    return torch.autocast(
        device_type="cuda",
        dtype=MODEL_DTYPE,
    )


# ==================================================================================================
# 44. PRE-FLIGHT TEST
# ==================================================================================================

print("\n" + "=" * 100)
print("PRE-FLIGHT QLoRA FORWARD TEST")
print("=" * 100)

preview_example = train_dataset[
    0
]

print(
    "Image:",
    preview_example[
        "image_path"
    ],
)

print(
    "Target:",
    label_to_target_text(
        preview_example[
            "label"
        ]
    ),
)

preview_batch_cpu = training_collator(
    [
        preview_example
    ]
)

preview_batch_gpu = move_batch_to_device(
    preview_batch_cpu
)

model.eval()

with torch.no_grad():

    with autocast_context():

        preview_outputs = model(
            **preview_batch_gpu
        )

preview_loss = float(
    preview_outputs.loss
    .detach()
    .float()
    .cpu()
)

print(
    f"Pre-flight loss: {preview_loss:.6f}"
)

if not np.isfinite(
    preview_loss
):

    raise RuntimeError(
        "Pre-flight loss is NaN or infinite."
    )

print("SUCCESS: QLoRA forward pass works.")

del preview_batch_cpu
del preview_batch_gpu
del preview_outputs

gc.collect()

torch.cuda.empty_cache()


# ==================================================================================================
# 45. OPTIMIZER
#
# SAME AdamW AS LoRA FOR CONTROLLED COMPARISON.
# ==================================================================================================

trainable_parameters = [
    parameter
    for parameter
    in model.parameters()
    if parameter.requires_grad
]

optimizer = torch.optim.AdamW(
    trainable_parameters,
    lr=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY,
)


# ==================================================================================================
# 46. SCHEDULER
# ==================================================================================================

optimizer_steps_per_epoch = math.ceil(
    len(
        train_loader
    )
    /
    GRADIENT_ACCUMULATION_STEPS
)

total_optimizer_steps = (
    optimizer_steps_per_epoch
    *
    NUM_EPOCHS
)

warmup_steps = int(
    total_optimizer_steps
    *
    WARMUP_RATIO
)

scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=warmup_steps,
    num_training_steps=total_optimizer_steps,
)


print("\n" + "=" * 100)
print("TRAINING SETTINGS")
print("=" * 100)

print("Epochs                :", NUM_EPOCHS)
print("Patience              :", EARLY_STOPPING_PATIENCE)
print("Training images       :", len(train_dataset))
print("Validation images     :", len(validation_dataset))
print("Batch size            :", TRAIN_BATCH_SIZE)
print("Gradient accumulation :", GRADIENT_ACCUMULATION_STEPS)

print(
    "Effective batch       :",
    TRAIN_BATCH_SIZE
    *
    GRADIENT_ACCUMULATION_STEPS,
)

print("Learning rate         :", LEARNING_RATE)
print("Weight decay          :", WEIGHT_DECAY)
print("Warmup ratio          :", WARMUP_RATIO)
print("LoRA r                :", LORA_R)
print("LoRA alpha            :", LORA_ALPHA)
print("LoRA dropout          :", LORA_DROPOUT)

print("\nQLoRA:")
print("Base weight bits      : 4")
print("Quantization          : NF4")
print("Double quantization   : True")
print("Compute dtype         :", MODEL_DTYPE)


# ==================================================================================================
# 47. VALIDATION LOSS
# ==================================================================================================

@torch.no_grad()
def calculate_validation_loss():

    model.eval()

    losses = []

    progress = tqdm(
        validation_loss_loader,
        desc="Validation loss",
        leave=False,
    )

    for batch in progress:

        batch = move_batch_to_device(
            batch
        )

        with autocast_context():

            outputs = model(
                **batch
            )

            loss = outputs.loss

        loss_value = float(
            loss
            .detach()
            .float()
            .cpu()
        )

        losses.append(
            loss_value
        )

        progress.set_postfix(
            loss=f"{loss_value:.4f}"
        )

        del batch
        del outputs
        del loss

    return float(
        np.mean(
            losses
        )
    )


# ==================================================================================================
# 48. NORMALIZE GENERATED PREDICTION
# ==================================================================================================

def normalize_prediction_text(
    output_text,
):

    text = str(
        output_text
    ).strip().lower()

    text = text.replace(
        "_",
        " ",
    )

    text = text.replace(
        "–",
        "-",
    )

    text = re.sub(
        r"\s+",
        " ",
        text,
    )

    # Check Non-seizure first.
    if re.search(
        r"\bnon[\s-]*seizure\b",
        text,
    ):

        return 0

    if re.search(
        r"\bseizure\b",
        text,
    ):

        return 1

    return None


# ==================================================================================================
# 49. SINGLE IMAGE GENERATION
# ==================================================================================================

@torch.no_grad()
def predict_single_image(
    image_path,
):

    model.eval()

    with Image.open(
        image_path
    ) as opened_image:

        image = opened_image.convert(
            "RGB"
        )

        messages = build_prompt_messages(
            image
        )

        inputs = processor.apply_chat_template(
            messages,
            add_generation_prompt=True,
            tokenize=True,
            return_dict=True,
            return_tensors="pt",
        )

    input_length = int(
        inputs[
            "input_ids"
        ].shape[
            1
        ]
    )

    inputs = move_batch_to_device(
        inputs
    )

    with autocast_context():

        generated = model.generate(
            **inputs,
            max_new_tokens=MAX_NEW_TOKENS,
            do_sample=False,
            num_beams=1,
            use_cache=True,
        )

    generated_tokens = generated[
        0,
        input_length:
    ]

    decoded = processor.decode(
        generated_tokens,
        skip_special_tokens=True,
    ).strip()

    prediction = normalize_prediction_text(
        decoded
    )

    return (
        decoded,
        prediction,
    )


# ==================================================================================================
# 50. METRICS
#
# Invalid output is counted as an incorrect prediction,
# matching your previous pipeline.
# ==================================================================================================

def calculate_binary_metrics(
    true_labels,
    predictions,
):

    metric_predictions = []

    invalid_count = 0

    for truth, prediction in zip(
        true_labels,
        predictions,
    ):

        if prediction is None:

            invalid_count += 1

            metric_predictions.append(
                1
                -
                int(
                    truth
                )
            )

        else:

            metric_predictions.append(
                int(
                    prediction
                )
            )

    y_true = np.asarray(
        true_labels,
        dtype=int,
    )

    y_pred = np.asarray(
        metric_predictions,
        dtype=int,
    )

    cm = confusion_matrix(
        y_true,
        y_pred,
        labels=[
            0,
            1,
        ],
    )

    tn, fp, fn, tp = cm.ravel()

    sensitivity = (
        tp
        /
        (
            tp
            +
            fn
        )
        if
        (
            tp
            +
            fn
        ) > 0
        else
        0.0
    )

    specificity = (
        tn
        /
        (
            tn
            +
            fp
        )
        if
        (
            tn
            +
            fp
        ) > 0
        else
        0.0
    )

    metrics = {

        "TN": int(tn),

        "FP": int(fp),

        "FN": int(fn),

        "TP": int(tp),

        "Sensitivity": float(
            sensitivity
        ),

        "Specificity": float(
            specificity
        ),

        "Balanced_Accuracy": float(
            balanced_accuracy_score(
                y_true,
                y_pred,
            )
        ),

        "Accuracy": float(
            accuracy_score(
                y_true,
                y_pred,
            )
        ),

        "Precision": float(
            precision_score(
                y_true,
                y_pred,
                zero_division=0,
            )
        ),

        "F1": float(
            f1_score(
                y_true,
                y_pred,
                zero_division=0,
            )
        ),

        "Invalid_Predictions": int(
            invalid_count
        ),
    }

    return (
        metrics,
        y_pred,
    )


# ==================================================================================================
# 51. VALIDATION GENERATION
# ==================================================================================================

@torch.no_grad()
def evaluate_validation_generation(
    epoch_number,
):

    model.eval()

    true_labels = []

    predictions = []

    progress = tqdm(
        range(
            len(
                validation_df
            )
        ),
        desc=f"Validation generation epoch {epoch_number}",
    )

    for index in progress:

        row = validation_df.iloc[
            index
        ]

        image_path = str(
            row[
                "_image_path"
            ]
        )

        raw_output, prediction = predict_single_image(
            image_path
        )

        true_label = int(
            row[
                "_label"
            ]
        )

        true_labels.append(
            true_label
        )

        predictions.append(
            prediction
        )

    metrics, y_pred = calculate_binary_metrics(
        true_labels,
        predictions,
    )

    return metrics


# ==================================================================================================
# 52. SAVE INITIAL EXPERIMENT CONFIG
# ==================================================================================================

experiment_config = {

    "Patient": 24,

    "Representation": "RAW fixed-scale EEG variance topomap",

    "Model": MODEL_ID,

    "Fine_Tuning_Method": "QLoRA",

    "Base_Model_Quantization": "4-bit",

    "Quantization_Type": "NF4",

    "Double_Quantization": True,

    "Quantization_Compute_Dtype": PRECISION_NAME,

    "Random_Seed": RANDOM_SEED,

    "System_Prompt": SYSTEM_PROMPT,

    "User_Prompt": USER_PROMPT,

    "Training_Metadata": TRAINING_METADATA_CSV,

    "Testing_Metadata": TESTING_METADATA_CSV,

    "Training_Examples": len(
        actual_train_df
    ),

    "Validation_Examples": len(
        validation_df
    ),

    "Testing_Examples": len(
        testing_df
    ),

    "LoRA_R": LORA_R,

    "LoRA_Alpha": LORA_ALPHA,

    "LoRA_Dropout": LORA_DROPOUT,

    "LoRA_Target_Module_Count": len(
        LORA_TARGET_MODULES
    ),

    "Trainable_Parameters": trainable_parameter_count,

    "Total_Parameters": total_parameter_count,

    "Trainable_Percentage": trainable_percentage,

    "Maximum_Epochs": NUM_EPOCHS,

    "Early_Stopping_Patience": EARLY_STOPPING_PATIENCE,

    "Learning_Rate": LEARNING_RATE,

    "Weight_Decay": WEIGHT_DECAY,

    "Physical_Batch_Size": TRAIN_BATCH_SIZE,

    "Gradient_Accumulation": GRADIENT_ACCUMULATION_STEPS,

    "Effective_Batch_Size": (
        TRAIN_BATCH_SIZE
        *
        GRADIENT_ACCUMULATION_STEPS
    ),

    "Warmup_Ratio": WARMUP_RATIO,

    "Max_Grad_Norm": MAX_GRAD_NORM,

    "GPU": GPU_NAME,

    "GPU_Memory_GB": GPU_MEMORY_GB,

    "PyTorch": torch.__version__,

    "Transformers": transformers.__version__,

    "PEFT": peft.__version__,

    "bitsandbytes": bnb.__version__,

    "Leakage_Check_Column": LEAKAGE_ID_COLUMN,

    "Used_Existing_LoRA_Split": bool(
        EXISTING_LORA_TRAIN_SPLIT is not None
        and
        EXISTING_LORA_VALIDATION_SPLIT is not None
    ),
}


with open(
    EXPERIMENT_CONFIG_JSON,
    "w",
    encoding="utf-8",
) as file:

    json.dump(
        experiment_config,
        file,
        indent=4,
    )


# ==================================================================================================
# 53. TRAINING VARIABLES
# ==================================================================================================

training_history = []

best_validation_balanced_accuracy = -float(
    "inf"
)

best_validation_loss = float(
    "inf"
)

best_epoch = None

BEST_ADAPTER_DIR = None

epochs_without_improvement = 0

stopped_early = False

early_stop_epoch = None


optimizer.zero_grad(
    set_to_none=True
)

gc.collect()

torch.cuda.empty_cache()

torch.cuda.reset_peak_memory_stats(
    DEVICE
)

training_start_time = time.time()


# ==================================================================================================
# 54. TRAIN
# ==================================================================================================

print("\n" + "=" * 100)
print("STARTING PATIENT 24 RAW MEDGEMMA-4B QLoRA TRAINING")
print("=" * 100)


for epoch in range(
    1,
    NUM_EPOCHS + 1,
):

    print("\n" + "=" * 100)

    print(
        f"EPOCH {epoch}/{NUM_EPOCHS}"
    )

    print("=" * 100)

    model.train()

    optimizer.zero_grad(
        set_to_none=True
    )

    epoch_loss_sum = 0.0

    epoch_batch_count = 0

    progress = tqdm(
        enumerate(
            train_loader
        ),
        total=len(
            train_loader
        ),
        desc=f"Training epoch {epoch}",
    )

    for batch_index, batch in progress:

        batch = move_batch_to_device(
            batch
        )

        with autocast_context():

            outputs = model(
                **batch
            )

            raw_loss = outputs.loss

            loss = (
                raw_loss
                /
                GRADIENT_ACCUMULATION_STEPS
            )

        loss.backward()

        raw_loss_value = float(
            raw_loss
            .detach()
            .float()
            .cpu()
        )

        epoch_loss_sum += raw_loss_value

        epoch_batch_count += 1

        should_step = (
            (
                (
                    batch_index
                    +
                    1
                )
#                 %
                GRADIENT_ACCUMULATION_STEPS
                ==
                0
            )
            or
            (
                (
                    batch_index
                    +
                    1
                )
                ==
                len(
                    train_loader
                )
            )
        )

        if should_step:

            torch.nn.utils.clip_grad_norm_(
                trainable_parameters,
                MAX_GRAD_NORM,
            )

            optimizer.step()

            scheduler.step()

            optimizer.zero_grad(
                set_to_none=True
            )

        progress.set_postfix(
            loss=f"{raw_loss_value:.4f}",
            lr=f"{scheduler.get_last_lr()[0]:.2e}",
        )

        del batch
        del outputs
        del raw_loss
        del loss

    mean_training_loss = (
        epoch_loss_sum
        /
        max(
            epoch_batch_count,
            1,
        )
    )

    print(
        f"\nMean training loss: "
        f"{mean_training_loss:.6f}"
    )


    # ----------------------------------------------------------------------------------------------
    # VALIDATION LOSS
    # ----------------------------------------------------------------------------------------------

    validation_loss = calculate_validation_loss()

    print(
        f"Validation loss: "
        f"{validation_loss:.6f}"
    )


    # ----------------------------------------------------------------------------------------------
    # VALIDATION GENERATION METRICS
    # ----------------------------------------------------------------------------------------------

    validation_metrics = evaluate_validation_generation(
        epoch
    )

    validation_ba = validation_metrics[
        "Balanced_Accuracy"
    ]

    print("\nVALIDATION METRICS")

    for key, value in validation_metrics.items():

        print(
            f"{key:22s}:",
            value,
        )


    # ----------------------------------------------------------------------------------------------
    # BEST CHECKPOINT DECISION
    #
    # Primary: highest validation balanced accuracy
    # Tie: lower validation loss
    # ----------------------------------------------------------------------------------------------

    ba_improved = (
        validation_ba
        >
        best_validation_balanced_accuracy
        +
        1e-12
    )

    ba_tied = (
        abs(
            validation_ba
            -
            best_validation_balanced_accuracy
        )
        <=
        1e-12
    )

    loss_improved_on_tie = (
        ba_tied
        and
        validation_loss
        <
        best_validation_loss
        -
        1e-12
    )

    is_new_best = (
        ba_improved
        or
        loss_improved_on_tie
    )


    history_row = {

        "epoch": epoch,

        "training_loss": mean_training_loss,

        "validation_loss": validation_loss,

        "validation_balanced_accuracy":
            validation_metrics[
                "Balanced_Accuracy"
            ],

        "validation_sensitivity":
            validation_metrics[
                "Sensitivity"
            ],

        "validation_specificity":
            validation_metrics[
                "Specificity"
            ],

        "validation_accuracy":
            validation_metrics[
                "Accuracy"
            ],

        "validation_precision":
            validation_metrics[
                "Precision"
            ],

        "validation_f1":
            validation_metrics[
                "F1"
            ],

        "validation_TN":
            validation_metrics[
                "TN"
            ],

        "validation_FP":
            validation_metrics[
                "FP"
            ],

        "validation_FN":
            validation_metrics[
                "FN"
            ],

        "validation_TP":
            validation_metrics[
                "TP"
            ],

        "validation_invalid":
            validation_metrics[
                "Invalid_Predictions"
            ],

        "new_best":
            bool(
                is_new_best
            ),

        "learning_rate":
            scheduler.get_last_lr()[0],
    }

    training_history.append(
        history_row
    )

    pd.DataFrame(
        training_history
    ).to_csv(
        TRAINING_HISTORY_CSV,
        index=False,
    )


    if is_new_best:

        best_validation_balanced_accuracy = (
            validation_ba
        )

        best_validation_loss = (
            validation_loss
        )

        best_epoch = epoch

        BEST_ADAPTER_DIR = os.path.join(
            BEST_ADAPTER_ROOT,
            f"epoch_{epoch:03d}_"
            f"BA_{validation_ba:.6f}_"
            f"loss_{validation_loss:.6f}",
        )

        os.makedirs(
            BEST_ADAPTER_DIR,
            exist_ok=True,
        )

        model.save_pretrained(
            BEST_ADAPTER_DIR
        )

        processor.save_pretrained(
            BEST_ADAPTER_DIR
        )

        epochs_without_improvement = 0

        print("\n" + "-" * 100)

        print("NEW BEST CHECKPOINT")

        print("Epoch         :", epoch)

        print(
            "Validation BA :",
            best_validation_balanced_accuracy,
        )

        print(
            "Validation loss:",
            best_validation_loss,
        )

        print(
            "Saved to:",
            BEST_ADAPTER_DIR,
        )

        print(
            f"Early stopping: 0/{EARLY_STOPPING_PATIENCE}"
        )

        print("-" * 100)

    else:

        epochs_without_improvement += 1

        print(
            f"\nNo new best checkpoint. "
            f"Patience: "
            f"{epochs_without_improvement}/"
            f"{EARLY_STOPPING_PATIENCE}"
        )


    gc.collect()

    torch.cuda.empty_cache()


    if (
        epochs_without_improvement
        >=
        EARLY_STOPPING_PATIENCE
    ):

        stopped_early = True

        early_stop_epoch = epoch

        print("\n" + "=" * 100)

        print("EARLY STOPPING TRIGGERED")

        print("=" * 100)

        print(
            "No new best checkpoint for",
            EARLY_STOPPING_PATIENCE,
            "consecutive epochs.",
        )

        print(
            "Stopping at epoch:",
            early_stop_epoch,
        )

        print(
            "Best epoch:",
            best_epoch,
        )

        break


training_end_time = time.time()

training_minutes = (
    training_end_time
    -
    training_start_time
) / 60.0


if BEST_ADAPTER_DIR is None:

    raise RuntimeError(
        "No best QLoRA adapter was saved."
    )


peak_training_allocated_gb = (
    torch.cuda.max_memory_allocated()
    /
    1024**3
)

peak_training_reserved_gb = (
    torch.cuda.max_memory_reserved()
    /
    1024**3
)


print("\n" + "=" * 100)
print("TRAINING COMPLETE")
print("=" * 100)

print("Best epoch            :", best_epoch)

print(
    "Best validation BA    :",
    best_validation_balanced_accuracy,
)

print(
    "Best validation loss  :",
    best_validation_loss,
)

print(
    "Stopped early         :",
    stopped_early,
)

print(
    f"Training time          : "
    f"{training_minutes:.2f} minutes"
)

print(
    f"Peak GPU allocated     : "
    f"{peak_training_allocated_gb:.2f} GB"
)


# ==================================================================================================
# 55. UPDATE EXPERIMENT CONFIG
# ==================================================================================================

experiment_config[
    "Best_Epoch"
] = best_epoch

experiment_config[
    "Best_Validation_Balanced_Accuracy"
] = best_validation_balanced_accuracy

experiment_config[
    "Best_Validation_Loss"
] = best_validation_loss

experiment_config[
    "Stopped_Early"
] = stopped_early

experiment_config[
    "Early_Stop_Epoch"
] = early_stop_epoch

experiment_config[
    "Best_Adapter_Directory"
] = BEST_ADAPTER_DIR

experiment_config[
    "Training_Time_Minutes"
] = training_minutes

experiment_config[
    "Peak_Training_GPU_Allocated_GB"
] = peak_training_allocated_gb


with open(
    EXPERIMENT_CONFIG_JSON,
    "w",
    encoding="utf-8",
) as file:

    json.dump(
        experiment_config,
        file,
        indent=4,
    )


# ==================================================================================================
# 56. FREE TRAINING MODEL
# ==================================================================================================

print("\nFreeing training model before final test...")

del model
del base_model
del optimizer
del scheduler

gc.collect()

torch.cuda.empty_cache()


# ==================================================================================================
# 57. RELOAD CLEAN 4-BIT BASE MODEL
# ==================================================================================================

print("\n" + "=" * 100)
print("RELOADING CLEAN 4-BIT MEDGEMMA FOR FINAL TEST")
print("=" * 100)

base_model = load_quantized_medgemma()

if hasattr(
    base_model.config,
    "use_cache",
):

    base_model.config.use_cache = True


# ==================================================================================================
# 58. LOAD BEST QLoRA ADAPTER
# ==================================================================================================

print("\n" + "=" * 100)
print("LOADING BEST QLoRA ADAPTER")
print("=" * 100)

model = PeftModel.from_pretrained(
    base_model,
    BEST_ADAPTER_DIR,
    is_trainable=False,
)

model.eval()

print(
    "Loaded best epoch:",
    best_epoch,
)

print(
    "Adapter:",
    BEST_ADAPTER_DIR,
)


# ==================================================================================================
# 59. FINAL BLINDED TEST
# ==================================================================================================

print("\n" + "=" * 100)
print("FINAL PATIENT 24 RAW BLINDED TEST")
print("=" * 100)

torch.cuda.reset_peak_memory_stats(
    DEVICE
)

test_start_time = time.time()

true_labels = []

predictions = []

prediction_rows = []


progress = tqdm(
    range(
        len(
            testing_df
        )
    ),
    desc="Final blinded test",
)


for index in progress:

    row = testing_df.iloc[
        index
    ]

    image_path = str(
        row[
            "_image_path"
        ]
    )

    # Model gets image + prompts only.
    raw_output, prediction = predict_single_image(
        image_path
    )

    # Ground truth used after generation.
    true_label = int(
        row[
            "_label"
        ]
    )

    true_labels.append(
        true_label
    )

    predictions.append(
        prediction
    )

    prediction_rows.append(
        {
            "test_index": index,

            "image_path": image_path,

            "true_label": true_label,

            "true_class": (
                "Seizure"
                if
                true_label == 1
                else
                "Non-seizure"
            ),

            "raw_model_output": raw_output,

            "predicted_label": prediction,

            "predicted_class": (
                "Seizure"
                if
                prediction == 1
                else
                (
                    "Non-seizure"
                    if
                    prediction == 0
                    else
                    "INVALID"
                )
            ),
        }
    )


final_metrics, final_metric_predictions = calculate_binary_metrics(
    true_labels,
    predictions,
)


for index, metric_prediction in enumerate(
    final_metric_predictions
):

    prediction_rows[
        index
    ][
        "metric_prediction"
    ] = int(
        metric_prediction
    )

    prediction_rows[
        index
    ][
        "correct_for_metric"
    ] = int(
        int(
            metric_prediction
        )
        ==
        int(
            true_labels[
                index
            ]
        )
    )


final_predictions_df = pd.DataFrame(
    prediction_rows
)

final_predictions_df.to_csv(
    FINAL_PREDICTIONS_CSV,
    index=False,
)


test_end_time = time.time()

test_minutes = (
    test_end_time
    -
    test_start_time
) / 60.0


peak_test_allocated_gb = (
    torch.cuda.max_memory_allocated()
    /
    1024**3
)

peak_test_reserved_gb = (
    torch.cuda.max_memory_reserved()
    /
    1024**3
)


# ==================================================================================================
# 60. SAVE FINAL METRICS
# ==================================================================================================

final_metrics[
    "Best_Epoch"
] = int(
    best_epoch
)

final_metrics[
    "Best_Validation_Balanced_Accuracy"
] = float(
    best_validation_balanced_accuracy
)

final_metrics[
    "Best_Validation_Loss"
] = float(
    best_validation_loss
)

final_metrics[
    "Final_Test_Time_Minutes"
] = float(
    test_minutes
)

final_metrics[
    "Peak_Test_GPU_Allocated_GB"
] = float(
    peak_test_allocated_gb
)

final_metrics[
    "Peak_Test_GPU_Reserved_GB"
] = float(
    peak_test_reserved_gb
)


with open(
    FINAL_METRICS_JSON,
    "w",
    encoding="utf-8",
) as file:

    json.dump(
        final_metrics,
        file,
        indent=4,
    )


# ==================================================================================================
# 61. SAVE CONFUSION MATRIX
# ==================================================================================================

confusion_df = pd.DataFrame(
    [
        {
            "TN": final_metrics[
                "TN"
            ],

            "FP": final_metrics[
                "FP"
            ],

            "FN": final_metrics[
                "FN"
            ],

            "TP": final_metrics[
                "TP"
            ],
        }
    ]
)

confusion_df.to_csv(
    CONFUSION_MATRIX_CSV,
    index=False,
)


# ==================================================================================================
# 62. FINAL REPORT
# ==================================================================================================

print("\n" + "=" * 100)
print("FINAL BLINDED TEST RESULTS")
print("=" * 100)

print(
    "TN:",
    final_metrics[
        "TN"
    ]
)

print(
    "FP:",
    final_metrics[
        "FP"
    ]
)

print(
    "FN:",
    final_metrics[
        "FN"
    ]
)

print(
    "TP:",
    final_metrics[
        "TP"
    ]
)

print(
    f"Sensitivity       : "
    f"{final_metrics['Sensitivity']:.6f}"
)

print(
    f"Specificity       : "
    f"{final_metrics['Specificity']:.6f}"
)

print(
    f"Balanced Accuracy : "
    f"{final_metrics['Balanced_Accuracy']:.6f}"
)

print(
    f"Accuracy          : "
    f"{final_metrics['Accuracy']:.6f}"
)

print(
    f"Precision         : "
    f"{final_metrics['Precision']:.6f}"
)

print(
    f"F1                : "
    f"{final_metrics['F1']:.6f}"
)

print(
    "Invalid outputs   :",
    final_metrics[
        "Invalid_Predictions"
    ],
)


print("\n" + "-" * 100)
print("BEST MODEL")
print("-" * 100)

print(
    "Best epoch:",
    best_epoch,
)

print(
    f"Best validation BA:"
    f" {best_validation_balanced_accuracy:.6f}"
)

print(
    f"Best validation loss:"
    f" {best_validation_loss:.6f}"
)


print("\n" + "-" * 100)
print("GPU / TIME")
print("-" * 100)

print(
    f"Training time           : "
    f"{training_minutes:.2f} min"
)

print(
    f"Final test time         : "
    f"{test_minutes:.2f} min"
)

print(
    f"Peak training allocated : "
    f"{peak_training_allocated_gb:.2f} GB"
)

print(
    f"Peak test allocated     : "
    f"{peak_test_allocated_gb:.2f} GB"
)


print("\n" + "=" * 100)
print("FILES SAVED")
print("=" * 100)

print("\nOutput folder:")
print(OUTPUT_ROOT)

print("\nBest QLoRA adapter:")
print(BEST_ADAPTER_DIR)

print("\nTraining split:")
print(TRAIN_SPLIT_CSV)

print("\nValidation split:")
print(VALIDATION_SPLIT_CSV)

print("\nTraining history:")
print(TRAINING_HISTORY_CSV)

print("\nFinal predictions:")
print(FINAL_PREDICTIONS_CSV)

print("\nFinal metrics:")
print(FINAL_METRICS_JSON)

print("\nConfusion matrix:")
print(CONFUSION_MATRIX_CSV)

print("\nExperiment config:")
print(EXPERIMENT_CONFIG_JSON)

print("\nTarget modules:")
print(TARGET_MODULES_TXT)


print("\n" + "=" * 100)
print("PATIENT 24 RAW MEDGEMMA-4B QLoRA EXPERIMENT COMPLETE")
print("=" * 100)